title: Who has the Sum?
email: d.c.koster@student.rug.nl
description:  >- # this means to ignore newlines until "baseurl:"
  The answer to the riddle "Who has the Sum?" using epistemic logic.        
  This project is part of the MSc course. Logical Aspects of Multi-Agent Systems by the University of Groningen (2024).
url: "https://dckoster.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

theme: jekyll-theme-slate

# Build settings
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

#minima:
#  social_links:
#    github: dckoster/DCKoster.github.io
