title: Who has the Sum?
email: d.c.koster@student.rug.nl
description:  >- # this means to ignore newlines until "baseurl:"
  The answer to the riddle "Who has the Sum?", and evaluations of variations, using epistemic logic.              
url: "https://dckoster.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
